[package]
name = "JWT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
serde_json = "1.0.23"
hmac = "0.12.0"
sha2 = "0.10.8"